version: '3.0'

services:
  postgres:
    container_name: postgres
    image: 'postgres:alpine'
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./.psql:/var/lib/psql
    restart: always
